export const ACTION_IDS = {
  app_mounted: "app.mounted",
  app_check_for_updates: "app.check_for_updates",
  app_editor_mount: "app.editor.mount",
  app_editor_unmount: "app.editor.unmount",
  app_handle_file_open: "app.handle_file_open",

  note_create: "note.create",
  note_open: "note.open",
  note_open_wiki_link: "note.open_wiki_link",
  note_insert_pasted_image: "note.insert_pasted_image",
  note_request_image_paste: "note.request_image_paste",
  note_update_image_paste_filename: "note.update_image_paste_filename",
  note_confirm_image_paste: "note.confirm_image_paste",
  note_cancel_image_paste: "note.cancel_image_paste",
  note_copy_markdown: "note.copy_markdown",
  note_request_delete: "note.request_delete",
  note_confirm_delete: "note.confirm_delete",
  note_cancel_delete: "note.cancel_delete",
  note_request_rename: "note.request_rename",
  note_update_rename_name: "note.update_rename_name",
  note_confirm_rename: "note.confirm_rename",
  note_confirm_rename_overwrite: "note.confirm_rename_overwrite",
  note_cancel_rename: "note.cancel_rename",
  note_retry_rename: "note.retry_rename",
  note_request_save: "note.request_save",
  note_update_save_path: "note.update_save_path",
  note_confirm_save: "note.confirm_save",
  note_confirm_save_overwrite: "note.confirm_save_overwrite",
  note_retry_save: "note.retry_save",
  note_cancel_save: "note.cancel_save",
  note_toggle_star: "note.toggle_star",

  vault_request_change: "vault.request_change",
  vault_close_change: "vault.close_change",
  vault_choose: "vault.choose",
  vault_select: "vault.select",
  vault_confirm_save_change: "vault.confirm_save_change",
  vault_confirm_discard_change: "vault.confirm_discard_change",
  vault_cancel_discard_change: "vault.cancel_discard_change",
  vault_select_pinned_slot: "vault.select_pinned_slot",
  vault_remove_from_registry: "vault.remove_from_registry",
  vault_toggle_pin: "vault.toggle_pin",
  vault_open_switcher: "vault.open_switcher",
  vault_fetch_git_info_for_list: "vault.fetch_git_info_for_list",
  vault_sync_index: "vault.sync_index",
  vault_reindex: "vault.reindex",

  folder_request_create: "folder.request_create",
  folder_update_create_name: "folder.update_create_name",
  folder_confirm_create: "folder.confirm_create",
  folder_cancel_create: "folder.cancel_create",
  folder_toggle: "folder.toggle",
  folder_load_more: "folder.load_more",
  folder_retry_load: "folder.retry_load",
  folder_collapse_all: "folder.collapse_all",
  folder_refresh_tree: "folder.refresh_tree",
  folder_request_delete: "folder.request_delete",
  folder_confirm_delete: "folder.confirm_delete",
  folder_cancel_delete: "folder.cancel_delete",
  folder_retry_delete: "folder.retry_delete",
  folder_request_rename: "folder.request_rename",
  folder_update_rename_name: "folder.update_rename_name",
  folder_confirm_rename: "folder.confirm_rename",
  folder_cancel_rename: "folder.cancel_rename",
  folder_retry_rename: "folder.retry_rename",
  folder_toggle_star: "folder.toggle_star",
  filetree_reveal_note: "filetree.reveal_note",
  filetree_select_item: "filetree.select_item",
  filetree_clear_selection: "filetree.clear_selection",
  filetree_move_items: "filetree.move_items",
  filetree_confirm_move_overwrite: "filetree.confirm_move_overwrite",
  filetree_skip_move_conflicts: "filetree.skip_move_conflicts",
  filetree_cancel_move_conflicts: "filetree.cancel_move_conflicts",
  filetree_toggle_star_selection: "filetree.toggle_star_selection",

  shell_open_url: "shell.open_url",

  ui_toggle_sidebar: "ui.toggle_sidebar",
  ui_select_folder: "ui.select_folder",
  ui_set_sidebar_view: "ui.set_sidebar_view",
  ui_toggle_context_rail: "ui.toggle_context_rail",
  ui_toggle_outline_panel: "ui.toggle_outline_panel",
  ui_open_vault_dashboard: "ui.open_vault_dashboard",
  ui_close_vault_dashboard: "ui.close_vault_dashboard",

  help_open: "help.open",
  help_close: "help.close",

  settings_open: "settings.open",
  settings_close: "settings.close",
  settings_update: "settings.update",
  settings_save: "settings.save",

  omnibar_toggle: "omnibar.toggle",
  omnibar_open: "omnibar.open",
  omnibar_open_all_vaults: "omnibar.open_all_vaults",
  omnibar_close: "omnibar.close",
  omnibar_set_query: "omnibar.set_query",
  omnibar_set_selected_index: "omnibar.set_selected_index",
  omnibar_set_scope: "omnibar.set_scope",
  omnibar_confirm_item: "omnibar.confirm_item",
  omnibar_confirm_cross_vault_open: "omnibar.confirm_cross_vault_open",
  omnibar_cancel_cross_vault_open: "omnibar.cancel_cross_vault_open",

  outline_scroll_to_heading: "outline.scroll_to_heading",

  find_in_file_toggle: "find_in_file.toggle",
  find_in_file_open: "find_in_file.open",
  find_in_file_close: "find_in_file.close",
  find_in_file_set_query: "find_in_file.set_query",
  find_in_file_next: "find_in_file.next",
  find_in_file_prev: "find_in_file.prev",

  tab_close: "tab.close",
  tab_close_other: "tab.close_other",
  tab_close_right: "tab.close_right",
  tab_close_all: "tab.close_all",
  tab_activate: "tab.activate",
  tab_activate_by_index: "tab.activate_by_index",
  tab_next: "tab.next",
  tab_prev: "tab.prev",
  tab_go_to_last_used: "tab.go_to_last_used",
  tab_reopen_closed: "tab.reopen_closed",
  tab_pin: "tab.pin",
  tab_unpin: "tab.unpin",
  tab_move_left: "tab.move_left",
  tab_move_right: "tab.move_right",
  tab_copy_path: "tab.copy_path",
  tab_reveal_in_tree: "tab.reveal_in_tree",
  tab_confirm_close_save: "tab.confirm_close_save",
  tab_confirm_close_discard: "tab.confirm_close_discard",
  tab_cancel_close: "tab.cancel_close",

  git_check_repo: "git.check_repo",
  git_init: "git.init",
  git_refresh_status: "git.refresh_status",
  git_commit_all: "git.commit_all",
  git_open_history: "git.open_history",
  git_close_history: "git.close_history",
  git_restore_version: "git.restore_version",
  git_open_checkpoint: "git.open_checkpoint",
  git_update_checkpoint_description: "git.update_checkpoint_description",
  git_confirm_checkpoint: "git.confirm_checkpoint",
  git_cancel_checkpoint: "git.cancel_checkpoint",
  git_select_commit: "git.select_commit",

  theme_load: "theme.load",
  theme_switch: "theme.switch",
  theme_create: "theme.create",
  theme_duplicate: "theme.duplicate",
  theme_rename: "theme.rename",
  theme_delete: "theme.delete",
  theme_update: "theme.update",
  theme_save: "theme.save",
  theme_revert: "theme.revert",

  hotkey_open_editor: "hotkey.open_editor",
  hotkey_close_editor: "hotkey.close_editor",
  hotkey_set_binding: "hotkey.set_binding",
  hotkey_clear_binding: "hotkey.clear_binding",
  hotkey_reset_all: "hotkey.reset_all",
  hotkey_reset_single: "hotkey.reset_single",

  split_view_toggle: "split_view.toggle",
  split_view_close: "split_view.close",
  split_view_mount: "split_view.mount",
  split_view_unmount: "split_view.unmount",
  split_view_set_active_pane: "split_view.set_active_pane",
  split_view_open_to_side: "split_view.open_to_side",
} as const;

export type ActionId = (typeof ACTION_IDS)[keyof typeof ACTION_IDS];
