import type { CommandDefinition } from "$lib/features/search/types/command_palette";

export const COMMANDS_REGISTRY: CommandDefinition[] = [
  {
    id: "create_new_note",
    label: "Create new note",
    description: "Create an untitled note in the current folder",
    keywords: ["new", "add", "create", "note", "file", "document"],
    icon: "file-plus",
  },
  {
    id: "save_note",
    label: "Save Note",
    description: "Save the current note",
    keywords: ["save note", "save current note", "write changes"],
    icon: "file-plus",
  },
  {
    id: "change_vault",
    label: "Change vault",
    description: "Switch to a different vault",
    keywords: ["switch", "vault", "folder", "workspace", "change", "open"],
    icon: "folder-open",
  },
  {
    id: "open_settings",
    label: "Settings",
    description: "Open application settings",
    keywords: ["settings", "preferences", "config", "options", "configure"],
    icon: "settings",
  },
  {
    id: "open_theme_settings",
    label: "Theme Settings",
    description: "Open theme and appearance settings",
    keywords: ["theme", "appearance", "dark mode", "light mode", "colors"],
    icon: "settings",
  },
  {
    id: "open_hotkeys",
    label: "Keyboard Shortcuts",
    description: "Configure keyboard shortcuts and hotkeys",
    keywords: [
      "hotkeys",
      "keyboard",
      "shortcuts",
      "keybindings",
      "keys",
      "remap",
      "bindings",
    ],
    icon: "keyboard",
  },
  {
    id: "toggle_sidebar",
    label: "Toggle Sidebar",
    description: "Show or hide the sidebar",
    keywords: ["sidebar", "navigation", "show sidebar", "hide sidebar"],
    icon: "folder-open",
  },
  {
    id: "find_in_note",
    label: "Find in Note",
    description: "Search within the current note",
    keywords: ["find", "find in note", "search in note", "current note"],
    icon: "settings",
  },
  {
    id: "open_help",
    label: "Open Help",
    description: "Show keyboard shortcuts and app help",
    keywords: ["help", "documentation", "shortcuts", "how to"],
    icon: "keyboard",
  },
  {
    id: "next_tab",
    label: "Next Tab",
    description: "Switch to the next open tab",
    keywords: ["next tab", "switch tab", "forward tab"],
    icon: "folder-open",
  },
  {
    id: "previous_tab",
    label: "Previous Tab",
    description: "Switch to the previous open tab",
    keywords: ["previous tab", "prev tab", "back tab"],
    icon: "folder-open",
  },
  {
    id: "last_used_tab",
    label: "Last Used Tab",
    description: "Switch to the previously active tab",
    keywords: ["last used tab", "previously used tab", "switch back"],
    icon: "history",
  },
  {
    id: "reopen_closed_tab",
    label: "Reopen Closed Tab",
    description: "Reopen the last closed tab",
    keywords: ["reopen tab", "undo close tab", "closed tab"],
    icon: "history",
  },
  {
    id: "sync_index",
    label: "Sync index",
    description: "Rescan vault files and sync search index",
    keywords: ["index", "sync", "search", "vault", "refresh", "rescan"],
    icon: "refresh-cw",
  },
  {
    id: "reindex_vault",
    label: "Reindex vault",
    description: "Rebuild search index for the current vault",
    keywords: ["index", "rebuild", "search", "vault", "reindex", "repair"],
    icon: "settings",
  },
  {
    id: "show_vault_dashboard",
    label: "Show vault dashboard",
    description: "Open vault dashboard overview",
    keywords: ["dashboard", "vault", "overview", "stats", "activity"],
    icon: "folder-open",
  },
  {
    id: "git_version_history",
    label: "Version History",
    description: "View version history for the current note",
    keywords: ["history", "versions", "git", "log", "timeline"],
    icon: "history",
  },
  {
    id: "git_create_checkpoint",
    label: "Create Checkpoint",
    description: "Save a named checkpoint of the current state",
    keywords: ["checkpoint", "snapshot", "save", "git", "commit"],
    icon: "bookmark",
  },
  {
    id: "git_init_repo",
    label: "Initialize Git Repository",
    description: "Initialize version control for this vault",
    keywords: ["git", "init", "repo", "repository", "version", "control"],
    icon: "git-branch",
  },
  {
    id: "toggle_links_panel",
    label: "Toggle Links Panel",
    description: "Show or hide backlinks and outlinks panel",
    keywords: ["links", "backlinks", "outlinks", "context", "panel", "sidebar"],
    icon: "link",
  },
  {
    id: "check_for_updates",
    label: "Check for Updates",
    description: "Check if a new version of Otterly is available",
    keywords: ["update", "upgrade", "version", "release", "new version"],
    icon: "refresh-cw",
  },
];
