import { ACTION_IDS } from "$lib/app/action_registry/action_ids";
import type { HotkeyBinding } from "$lib/features/hotkey/types/hotkey_config";

export const DEFAULT_HOTKEYS: HotkeyBinding[] = [
  {
    action_id: ACTION_IDS.omnibar_toggle,
    key: "CmdOrCtrl+P",
    phase: "capture",
    label: "Command Palette",
    description: "Open or close the command palette",
    category: "general",
  },
  {
    action_id: ACTION_IDS.help_open,
    key: "F1",
    phase: "capture",
    label: "Open Help",
    description: "Open the help dialog",
    category: "general",
  },
  {
    action_id: ACTION_IDS.omnibar_open,
    key: "CmdOrCtrl+O",
    phase: "capture",
    label: "Open Notes",
    description: "Open omnibar in note search mode",
    category: "general",
  },
  {
    action_id: ACTION_IDS.note_request_save,
    key: "CmdOrCtrl+S",
    phase: "bubble",
    label: "Save Note",
    description: "Save the current note",
    category: "general",
  },
  {
    action_id: ACTION_IDS.settings_open,
    key: "CmdOrCtrl+,",
    phase: "capture",
    label: "Open Settings",
    description: "Open the settings dialog",
    category: "general",
  },
  {
    action_id: ACTION_IDS.ui_toggle_sidebar,
    key: "CmdOrCtrl+Shift+B",
    phase: "capture",
    label: "Toggle Sidebar",
    description: "Show or hide the sidebar",
    category: "navigation",
  },
  {
    action_id: ACTION_IDS.find_in_file_toggle,
    key: "CmdOrCtrl+F",
    phase: "capture",
    label: "Find in File",
    description: "Search within the current file",
    category: "navigation",
  },
  {
    action_id: ACTION_IDS.vault_open_switcher,
    key: "CmdOrCtrl+Shift+V",
    phase: "capture",
    label: "Quick Switch Vault",
    description: "Open the vault switcher dropdown",
    category: "navigation",
  },
  {
    action_id: ACTION_IDS.ui_toggle_outline_panel,
    key: "CmdOrCtrl+Shift+O",
    phase: "capture",
    label: "Toggle Outline Panel",
    description: "Show or hide the document outline",
    category: "navigation",
  },
  {
    action_id: ACTION_IDS.ui_open_vault_dashboard,
    key: "CmdOrCtrl+Shift+D",
    phase: "capture",
    label: "Open Vault Dashboard",
    description: "View vault statistics and overview",
    category: "navigation",
  },
  {
    action_id: ACTION_IDS.omnibar_open_all_vaults,
    key: "CmdOrCtrl+Shift+F",
    phase: "capture",
    label: "Search All Vaults",
    description: "Search notes across all vaults",
    category: "navigation",
  },
  {
    action_id: ACTION_IDS.git_open_history,
    key: "CmdOrCtrl+Shift+H",
    phase: "capture",
    label: "Open Version History",
    description: "View git history for current note",
    category: "navigation",
  },
  {
    action_id: ACTION_IDS.ui_toggle_context_rail,
    key: "CmdOrCtrl+Shift+L",
    phase: "capture",
    label: "Toggle Links Panel",
    description: "Show or hide the links panel",
    category: "navigation",
  },
  {
    action_id: ACTION_IDS.tab_close,
    key: "CmdOrCtrl+W",
    phase: "capture",
    label: "Close Tab",
    description: "Close the current tab",
    category: "tabs",
  },
  {
    action_id: ACTION_IDS.tab_reopen_closed,
    key: "CmdOrCtrl+Shift+T",
    phase: "capture",
    label: "Reopen Closed Tab",
    description: "Reopen the last closed tab",
    category: "tabs",
  },
  {
    action_id: ACTION_IDS.tab_next,
    key: "CmdOrCtrl+J",
    phase: "capture",
    label: "Next Tab",
    description: "Switch to the next tab",
    category: "tabs",
  },
  {
    action_id: ACTION_IDS.tab_prev,
    key: "CmdOrCtrl+K",
    phase: "capture",
    label: "Previous Tab",
    description: "Switch to the previous tab",
    category: "tabs",
  },
  {
    action_id: ACTION_IDS.tab_go_to_last_used,
    key: "CmdOrCtrl+`",
    phase: "capture",
    label: "Switch to Last Used Tab",
    description: "Switch to the previously active tab",
    category: "tabs",
  },
  {
    action_id: ACTION_IDS.tab_move_left,
    key: "CmdOrCtrl+Alt+ArrowLeft",
    phase: "capture",
    label: "Move Tab Left",
    description: "Move current tab to the left",
    category: "tabs",
  },
  {
    action_id: ACTION_IDS.tab_move_right,
    key: "CmdOrCtrl+Alt+ArrowRight",
    phase: "capture",
    label: "Move Tab Right",
    description: "Move current tab to the right",
    category: "tabs",
  },
  {
    action_id: ACTION_IDS.note_create,
    key: "CmdOrCtrl+N",
    phase: "bubble",
    label: "Create Note",
    description: "Create a new note",
    category: "editing",
  },
  {
    action_id: ACTION_IDS.find_in_file_next,
    key: "CmdOrCtrl+G",
    phase: "bubble",
    label: "Find Next",
    description: "Jump to next search match",
    category: "editing",
  },
  {
    action_id: ACTION_IDS.find_in_file_prev,
    key: "CmdOrCtrl+Shift+G",
    phase: "bubble",
    label: "Find Previous",
    description: "Jump to previous search match",
    category: "editing",
  },
  {
    action_id: ACTION_IDS.split_view_toggle,
    key: "CmdOrCtrl+\\",
    phase: "capture",
    label: "Toggle Split View",
    description: "Split the editor to view two documents side by side",
    category: "navigation",
  },
];
